# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good_kind',
            fields=[
                ('kind_id', models.AutoField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=4)),
                ('second', models.CharField(max_length=8)),
                ('third', models.CharField(max_length=12)),
                ('active1', models.CharField(max_length=8)),
                ('active2', models.CharField(max_length=8)),
            ],
            managers=[
                ('goodkingmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Goods_mes',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('good_name', models.CharField(max_length=15)),
                ('good_price', models.IntegerField()),
                ('good_inst', tinymce.models.HTMLField()),
                ('good_img', models.ImageField(null=True, upload_to='static/img/Goodsimg/Goods/')),
            ],
            managers=[
                ('goodmesmanage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='good_kind',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_mes'),
        ),
    ]
