# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_info',
            fields=[
                ('good_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_num', models.IntegerField()),
                ('rema_num', models.IntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_mes')),
            ],
            managers=[
                ('goodinfo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_account', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=10)),
                ('seller_phone', models.CharField(max_length=11)),
                ('seller_pwd', models.CharField(max_length=16)),
                ('seller_header', models.ImageField(null=True, upload_to='static/img/Storeimg/seller/')),
            ],
            managers=[
                ('sellermanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('store_pic', models.ImageField(null=True, upload_to='static/img/Storeimg/img/')),
                ('store_deta', tinymce.models.HTMLField()),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Seller')),
            ],
            managers=[
                ('storemanage', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='goods_info',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Stores'),
        ),
    ]
