# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_good_num', models.IntegerField()),
                ('ord_good_price', models.IntegerField()),
                ('ord_user_addr', models.CharField(max_length=50)),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_mes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Users')),
            ],
            managers=[
                ('ordermanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
